name: sofomo_github
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  path: any
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  get_it: ^8.0.3
  injectable: ^2.4.4
  url_launcher: ^6.3.1
  bloc: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.5
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.2.0
  freezed: ^3.0.6
  
dependency_overrides:
  analyzer: ^6.2.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


