// Mocks generated by Mockito 5.4.5 from annotations
// in sofomo_github/test/repository/github_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sofomo_github/data/model/issue_dto.dart' as _i5;
import 'package:sofomo_github/data/model/repository_api_response.dart' as _i2;
import 'package:sofomo_github/data/source/api/api_client.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRepositoryApiModel_0 extends _i1.SmartFake
    implements _i2.RepositoryApiModel {
  _FakeRepositoryApiModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RepositoryApiModel> getRepositories(String? searchText) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositories, [searchText]),
            returnValue: _i4.Future<_i2.RepositoryApiModel>.value(
              _FakeRepositoryApiModel_0(
                this,
                Invocation.method(#getRepositories, [searchText]),
              ),
            ),
          )
          as _i4.Future<_i2.RepositoryApiModel>);

  @override
  _i4.Future<List<_i5.IssueDto>> getIssues(String? fullName) =>
      (super.noSuchMethod(
            Invocation.method(#getIssues, [fullName]),
            returnValue: _i4.Future<List<_i5.IssueDto>>.value(<_i5.IssueDto>[]),
          )
          as _i4.Future<List<_i5.IssueDto>>);
}
